### PR TITLE
Adds some status info from any thermostats

### PR DESCRIPTION
**Pull request by hufman**
Our house has the ADT Smart Thermostat, which is a rebranded Alarm Dot Com thermostat. I found that ADT's similar API provides access to the thermostat data, and extended my local copy of this plugin to expose some of its information.

The resulting sensor_status looks like:
`...Bedroom is Closed, System is Closed, Thermostat_ambientTemp is 75.0, Thermostat_coolSetpoint is 76.0, Thermostat_fanMode is 0, Thermostat_heatSetpoint is 69.0, Thermostat_humidityLevel is 44.0, Thermostat_state is 3`

### CODE REVIEW

**Comment by uvjustin** [comment]
Seems fine to me, but I'm not sure if everyone's portal has the thermostat section. Maybe add the thermostat option as an optional parameter to async_update()?
Something like:
`async def async_update(self, thermostats=False):`
and then test for thermostats before loading the thermostat data.
We can pass thermostats in from the yaml to the custom component to the library.

**Comment by hufman** [comment]
Oh interesting, I would have assumed it would just return an empty list.
I like that the configuration for this component is very minimal, and I don't want to complicate the config with an additional flag. The REST call to fetch [data about the main system](https://github.com/uvjustin/pyalarmdotcomajax/blob/master/pyalarmdotcomajax/pyalarmdotcomajax.py#L140) also returns data about the available devices. Instead of a user-provided flag, this response could be used to automatically set a flag to enable the thermostat fetching only if any thermostats are found in the main system information. Can I implement that instead of a user flag?

**Comment by uvjustin** [comment]
> Oh interesting, I would have assumed it would just return an empty list.
I would think so too, but it's undocumented and we don't know. We saw that the arming options available in the portal and to REST call can vary: https://github.com/uvjustin/alarmdotcomajax/issues/15#issuecomment-691482336

> I like that the configuration for this component is very minimal, and I don't want to complicate the config with an additional flag. The REST call to fetch [data about the main system](https://github.com/uvjustin/pyalarmdotcomajax/blob/master/pyalarmdotcomajax/pyalarmdotcomajax.py#L140) also returns data about the available devices. Instead of a user-provided flag, this response could be used to automatically set a flag to enable the thermostat fetching only if any thermostats are found in the main system information. Can I implement that instead of a user flag?

That sounds fine. Are there any other sensors that are exposed?
The other thing to think about is whether we want to send back the info to HA together with the zone status or separate it out. I agree with you on keeping it simple (I don't even use the sensor states myself) and would prefer not to make many changes, but it is probably cleaner if we do take out the temperature status.
Just out of curiosity, why do you have the thermostats set up through ADC? Wouldn't it be easier to hook them into HA directly? Is it not possible as they are somehow paired to the ADT hub?

**Comment by uvjustin** [comment]
Sorry for the delay - it looks good to me. Although I won't be able to test the thermostat functionality, I will test it on my end just to make sure there are no problems with my setup.

**Pull request merged**
