### PR TITLE
Retrieve detailed sensor attributes

### PR DESCRIPTION
**Pull request by elahd**
This change:

1. Collects detailed sensor attributes related to open/close state, battery status, and error status. Intent is to submit a PR to [uvjustin/alarmdotcom](https://github.com/uvjustin/alarmdotcom) to add sensor devices to HA without having to manually create template binary sensors.
2. Added .gitignore for easier commits.
3. Started a list of deviceType mappings.

### CODE REVIEW

**Comment by uvjustin** [comment]
Thanks for this PR.
I don't know much about the .gitignore or .vscode settings, but they look fine to me.
A few questions:
Why do we need to make _systemid public?
Is the device type help page supposed to be included in a readme?
I haven't looked at the interface in a while but when some of the 2FA logins fail it causes errors looking up a non existent key as we access using [] instead of get. I've thought about changing that before to fail more gracefully, but haven't bothered so far. However I'd like to avoid even more similar problems down the road - for this PR, are those keys in sensor[][] always available?

**Comment by elahd** [comment]
Thanks for reviewing!

- **.gitignore/.vscode:** .gitignore ensures that sensitive files and build artifacts don't get pushed into the repo. In my case, I have a local test.py script in the project root that has my alarm.com credentials that I didn't want to accidentally commit. I used the [GitHub standard .gitignore file for Python](https://github.com/github/gitignore/blob/main/Python.gitignore). The .vscode config file sets black to the default formatter for anyone developing in VS Code.
- **_systemid:** I made this public so that it can be used as a unique identifier for Home Assistant's new Config Flow Handler based workflow. Essentially, this would prevent someone from accidentally adding the same alarm system twice, but would allow someone with two different alarm.com systems to add both. See https://developers.home-assistant.io/docs/config_entries_config_flow_handler#unique-ids.
- **Device type help page:** I didn't want to make assumptions about how you wanted to keep the main readme, so I thought it was safer to insert as a separate file. If you don't mind, I can add it to the bottom of the main readme.
- **Empty Keys:** I'm not sure of whether those are always available, but I also didn't know about Python's get() method on dicts. I'll update the code and will resubmit.

**Comment by uvjustin** [comment]
> Thanks for reviewing!
> 
> * **.gitignore/.vscode:** .gitignore ensures that sensitive files and build artifacts don't get pushed into the repo. In my case, I have a local test.py script in the project root that has my alarm.com credentials that I didn't want to accidentally commit. I used the [GitHub standard .gitignore file for Python](https://github.com/github/gitignore/blob/main/Python.gitignore). The .vscode config file sets black to the default formatter for anyone developing in VS Code.

Sure, that looks fine to me.

> * **_systemid:** I made this public so that it can be used as a unique identifier for Home Assistant's new Config Flow Handler based workflow. Essentially, this would prevent someone from accidentally adding the same alarm system twice, but would allow someone with two different alarm.com systems to add both. See https://developers.home-assistant.io/docs/config_entries_config_flow_handler#unique-ids.

Got it. I'm familiar with the unique id/config flow, and systemid seems like a good choice. Are you planning on making a config flow for the custom component?

> * **Device type help page:** I didn't want to make assumptions about how you wanted to keep the main readme, so I thought it was safer to insert as a separate file. If you don't mind, I can add it to the bottom of the main readme.

Sure, please add it there.

> * **Empty Keys:** I'm not sure of whether those are always available, but I also didn't know about Python's get() method on dicts. I'll update the code and will resubmit.

If we are sure the keys are always there then it's more efficient and less cluttered to use [], but if we're not sure then let's play it safe.

**Comment by elahd** [comment]
Should be good now with the device types list and .get().

On switching to config flow, I'm not sure of how much time I'll have to modify the add-in, but wanted to have systemid available just in case!

**Comment by uvjustin** [comment]
Looks good, thanks!

**Pull request merged**
