### PR TITLE
Add "armed night" to the alarm state map

### PR DESCRIPTION
**Pull request by hufman**
My alarm panel offers a Armed Night mode, and this adds the index for this mode to the parsing code.

### CODE REVIEW

**Comment by uvjustin** [comment]
Thanks, merged. Was this state added recently?

**Comment by hufman** [comment]
I don't think so, the alarm panel has offered that choice for the whole year we've had it, but I've only tried to use this state in Home Assistant this week :)

**Comment by uvjustin** [comment]
I see, was wondering if that could cause "Unable to extract state data" errors like what @mikesalz is seeing here https://github.com/uvjustin/alarmdotcom/issues/35. If there are potentially other states which causes a KeyError on the STATEMAP, I should probably use get for the STATEMAP and return an unknown state to HA if that fails.

**Comment by hufman** [comment]
Hmmm no, I don't see that message in my logs, I see this one:
```
2021-03-30 22:55:29 ERROR (MainThread) [homeassistant.helpers.entity] Update for alarm_control_panel.alarm_com fails
Traceback (most recent call last):
  File "/opt/homeassistant/venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 277, in async_update_ha_state
    await self.async_device_update()
  File "/opt/homeassistant/venv/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 473, in async_device_update
    raise exc
  File "/opt/homeassistant/.homeassistant/custom_components/alarmdotcom/alarm_control_panel.py", line 160, in async_update
    await self._alarm.async_update()
  File "/opt/homeassistant/venv/lib/python3.9/site-packages/pyalarmdotcomajax/pyalarmdotcomajax.py", line 229, in async_update
    self.state = self.STATEMAP[self.state]
IndexError: tuple index out of range
```

**Comment by uvjustin** [comment]
Oh right, it's a tuple, not a dict.

**Comment by hufman** [comment]
Thank you again for the quick response! Can you also look at the frontend portion? https://github.com/uvjustin/alarmdotcom/pull/37

**Comment by uvjustin** [comment]
Sorry I didn't see your PR there and I already made the same changes after merging the PR here.

**Pull request merged**
