### PR TITLE
Major changes to support enhanced Home Assistant integration.

### PR DESCRIPTION
**Pull request by elahd**
I started work on exposing individual sensors and devices through your "alarmdotcom" Home Assistant integration and realized that I needed more data with more structure from pyalarmdotcomajax. These changes are extensive, breaking, and I'm not sure of whether they're desired. I'm happy to release this as a new package if you'd prefer to keep things separate or to join this project as a maintainer to help keep it running. A list of changes are below:

### Device Support

**Supported Device Types**

1. Systems
2. Partitions
3. Sensors
4. Garage Doors (now supports opening and closing actions)
5. Locks (Closes #17)

**Removed support for Thermostats**

I'd like to re-implement this after seeing the endpoint's JSON response. I don't currently have access to an Alarm.com compatible thermostat.

### CLI

I built a CLI using some of the code submitted by @kevin-david (closes #16). I formalized argument parsing using [argparse](https://docs.python.org/3/library/argparse.html) from Python's standard library.

### Code Structure

1. I made this "more" object oriented. Fundamentally the user interacts with an `ADCController` which communicates with the API and creates `ADCBaseElement`s that represent Alarm.com devices. `ADCController` has implementations for both ADT and Protection1 variants. `ADCBaseElement` has implementations to represent all of the supported devices listed above.
2. I used constants to allow pyalarmdotcomajax to standardize output wherever possible/sensible.

### CODE REVIEW

**Comment by uvjustin** [comment]
This sounds great. I have a relatively basic ADC install on my end so I haven't used much outside the core functionality, and I haven't had the need/setup/motivation to make any substantive changes in a while (since the 2FA stuff). It would be good to have some others join as maintainers to help with bugs or to add features. Going off recent PRs, I'll add you and @kevin-david. We can also add @vegardengen or @hufman if they have any interest.
Previously the releases were published ad-hoc, but if we are going to have multiple maintainers, we should probably also set up some CI actions to publish to PyPI and use tagged releases. The integration should have a pinned version of the library, so generally we would release a new library first (if necessary) and then release a new integration against it.
As for the classes you mentioned, IIRC the ADT/Protection1 stuff is probably not needed anymore. I think it was used briefly as providers were switching to 2FA. We'll need to double check that or confirm with some ADT/Protection1 users.

**Comment by elahd** [comment]
Sounds great, thanks! Would be helpful to have some sort of chat going, as well. Seems like Discord is the defacto place to do this. Would that work for you?

I'd also like to build out some testing around the package. I'll post back here when I think my updates are stable enough for review. You can see by the commits that I've been chugging away building updates.

**Comment by kevin-david** [comment]
@elahd let me know when you're ready to have someone else test out your version of the integration - i am happy to do it!

**Comment by elahd** [comment]
Thanks @kevin-david! I'm going to publish a new version of this library, then will release a dev version of the new HA add-in. Leaving it to you to add your obfuscated users.noreply.github.com email address to the maintainers list in setup.cfg.

@uvjustin Are you able to add me as a maintainer on pypi? My username is elahd.

**Comment by uvjustin** [comment]
Sure, I'll add you there. Later on we can set up CI to publish a new package with tagged releases using secrets stored in this repo.
Although I haven't looked at everything in detail, this PR seems fine, and since it's a major refactor I think it might be hard to go through line by line. Since we have a few maintainers now, perhaps we should try to have a review process for future PRs? Also, we should probably bump at least the minor version since it's a big overhaul.

**Comment by vegardengen** [comment]
Personally, I have been trying to test this. I updated from master, and discovered I no longer have the main function available.

@elahd how do you test this?

**Comment by elahd** [comment]
@vegardengen 

You can test it using one of the two methods below. Both methods will let you import pyalarmdotcomajax into other python projects and will install the command line application into your system path. You should be able to run `adc` from any directory to use the cli.

To start, you'll need to make sure that your version of python is >=3.9. Then, choose your adventure:

## via git

Use this method if you plan on doing dev work on pyalarmdotcomajax itself. This will install the checked-out copy of pyalarmdotcomajax via symlink. That is, you'll be able to edit code and see the changes reflected in your python environment in real time, without rebuilding.

```bash
git clone https://github.com/uvjustin/pyalarmdotcomajax.git
cd pyalarmdotcomajax
pip install --editable .
```

## via pypi

Use this version if you just want to use pyalarmdotcomajax in other projects or via its cli.

```bash
pip install pyalarmdotcomajax==2.1.0b0
```

-----

Separately, @uvjustin, would you be able to add a PyPi API key as a repo secret, or give me access to the repo's settings? I'd like to set up automatic publishing to PyPi whenever a GitHub release is published.

Also, we probably need a better way to chat. Does Discord work for you? My username there is, shockingly, elahd.

Thanks!!

**Comment by uvjustin** [comment]
Sure, I will add the secrets to the repo here.
Separately, while I really appreciate you taking up the mantle here and moving things forward, I don't think we should change the versioning schema. We jumped from 0.1.x to 2.x.x. which doesn't make sense to me. I think we should have either bumped the minor version (ie gone to 0.2.x) or bumped the major version (to 1.x.x). As you've only released beta versions on PyPI so far, I think it's probably still possible to yank those and go back to one of the aforementioned version numbers.

**Comment by uvjustin** [comment]
@elahd I've added a pypi token as a repo secret.

**Comment by elahd** [comment]
Thanks!

Agreed on the versioning schema. Honestly, I'm not sure why I did that. I'll change it later today.

**Comment by elahd** [comment]
> @elahd let me know when you're ready to have someone else test out your version of the integration - i am happy to do it!

@kevin-david v0.2.0 of the integration is released via HACS. You should be able to download it if you enable beta releases for the component.

**Comment by kevin-david** [comment]
@elahd thanks! i finally got around to trying this out. setup is much easier and it's great to see the expanded sensors

that said, it seems like there is a problem with locks - both of mine are showing up in the "Malfunction" state. The lock and unlock commands work properly but this causes a problem when rendering the current state on lovelace

**Comment by elahd** [comment]
Awesome -- thanks! Any idea what may be causing the malfunction status? I only have an alarm system with door/window sensors and smoke/co detectors. I'm flying blind on locks and garage doors.

I also made some changes over the past couple of days relating to the malfunction state in response to feedback on https://github.com/uvjustin/alarmdotcom. Which version of the add-in do you have installed?

**Comment by vegardengen** [comment]
I created a pull request that was triggered by me trying to get started on this issue.

I have the same problem, and will have a look at it.

**Comment by vegardengen** [comment]
I nailed the malfunctioning issue, it was a matter of replacing strings with correct numeric values in DeviceInfo for locks.

I'm going to see if I can pull a bit more info from the state to add as attributes before I create the pull request, but it will definitely come this weekend.

@elahd can we agree that if we add "WIP" to a pull request, it's not in a mergeable state? If so, I can create the PR while working and be a bit more opaque and let others comment in between.

**Pull request merged**
